DynamoPost/Models/Descripcion.cs
using Amazon.DynamoDBv2.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynamoPost.Models
{
    public class Descripcion
    {
        [DynamoDBProperty("pelo")]
        public String Pelo { get; set; }

        [DynamoDBProperty("ojos")]
        public String Ojos { get; set; }

        [DynamoDBProperty("villano")]
        public bool Villano { get; set; }
    }
}

DynamoPost/Models/ErrorViewModel.cs
using System;

namespace DynamoPost.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DynamoPost/Models/Personaje.cs
using Amazon.DynamoDBv2.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynamoPost.Models
{
    [DynamoDBTable("dynamopersonajes")]
    public class Personaje
    {
        [DynamoDBProperty("idpersonaje")]
        [DynamoDBHashKey]
        public int IdPersonaje { get; set; }

        [DynamoDBProperty("pelicula")]
        public String Pelicula { get; set; }

        [DynamoDBProperty("nombre")]
        public String Nombre { get; set; }

        [DynamoDBProperty("descripcion")]
        public Descripcion Descripcion { get; set; }

    }
}

DynamoPost/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DynamoPost.Models;

namespace DynamoPost.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DynamoPost/Controllers/PersonajesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DynamoPost.Models;
using DynamoPost.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace DynamoPost.Controllers
{
    public class PersonajesController : Controller
    {
        PersonajesServiceDynamodb ServiceDynamo;

        public PersonajesController(PersonajesServiceDynamodb serviceDynamo)
        {
            this.ServiceDynamo = serviceDynamo;
        }

        public async Task<IActionResult> Index()
        {
            return View(await this.ServiceDynamo.GetPersonajes());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Personaje personaje, String incluirdes, String ojos, String pelo, bool villano)
        {
            if (incluirdes != null)
            {
                personaje.Descripcion = new Descripcion();
                personaje.Descripcion.Ojos = ojos;
                personaje.Descripcion.Villano = villano;
            }

            await this.ServiceDynamo.CreatePersonaje(personaje);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int id)
        {
            //Buscamos al personaje:
            Personaje personaje = await this.ServiceDynamo.FindPersonaje(id);
            return View(personaje);
        }

      
        public async Task<IActionResult> Delete(int id)
        {
            Personaje personaje =
            await this.ServiceDynamo.FindPersonaje(id);
            await this.ServiceDynamo.DeletePersonaje(id);
            return RedirectToAction("index");
        }


    }
}

DynamoPost/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DynamoPost/Views/Personajes/Create.cshtml
@model DynamoPost.Models.Personaje
@{
    ViewData["Title"] = "Create";
}
<h1>Create</h1>
<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersonaje" class="control-label"></label>
                <input asp-for="IdPersonaje" class="form-control" />
                <span asp-validation-for="IdPersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pelicula" class="control-label"></label>
                <input asp-for="Pelicula" class="form-control" />
                <span asp-validation-for="Pelicula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="checkbox" name="incluirdes" value="yes" class="form-control" />Incluir descripción <br />
                <label> Ojos </label>
                <input type="text" name="ojos" class="form-control" /><br />
                <label> Pelo </label>
                <input type="text" name="pelo" class="form-control" /><br />
                <label> Villano </label>
                <input type="checkbox" name="villano" value="si" class="form-control" /> Si
                <input type="checkbox" name="villano" value="no" class="form-control" /> No
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DynamoPost/Views/Personajes/Details.cshtml
@model DynamoPost.Models.Personaje

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Personaje</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdPersonaje)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdPersonaje)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pelicula)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pelicula)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    @if (Model.Descripcion != null)
    {
        <h2 style="color:blue">
            Ojos: @Model.Descripcion.Ojos,
            Pelo: @Model.Descripcion.Pelo,
            Villano: @Model.Descripcion.Villano
        </h2>
    }
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdPersonaje}) |
    <a asp-action="Index">Back to List</a>
</div>

DynamoPost/Views/Personajes/Index.cshtml
@model IEnumerable<DynamoPost.Models.Personaje>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pelicula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPersonaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pelicula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.IdPersonaje }) |
                @Html.ActionLink("Details", "Details", new { id= item.IdPersonaje }) |
                @Html.ActionLink("Delete", "Delete", new { id= item.IdPersonaje })
            </td>
        </tr>
}
    </tbody>
</table>

DynamoPost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DynamoPost</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DynamoPost</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personajes" asp-action="Index"> AWS DynamoDb </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DynamoPost - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>